# Generated by Django 3.2.8 on 2021-11-18 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.IntegerField()),
                ('bid_lot_id', models.IntegerField()),
                ('bid_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LotCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='LotImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleimage', models.CharField(max_length=64)),
                ('lot_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_name', models.CharField(max_length=64)),
                ('lot_price', models.IntegerField()),
                ('lot_description', models.CharField(max_length=256)),
                ('lot_date', models.DateTimeField(auto_now=True)),
                ('lot_status', models.BooleanField()),
                ('lot_author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lot_bid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lotbid', to='auctions.bid')),
                ('lot_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.lotcategory')),
                ('lot_viewimage', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imagelot', to='auctions.lotimage')),
            ],
        ),
    ]
